### ISSUE TITLE
[Bug]: Drawer unswipeable on mobile

### ISSUE THREAD

**Issue by Noorae** [Pearl-image-comparer/Pearl#127]
Fix added to Drawer.tsx  to prevent the map from dragging when the menu is opened causes the SwipeableDrawer to not open on touch.

Problem in file Drawer.tsx:
```
useEffect(() => {
   if (containerRef.current)
   L.DomEvent.disableClickPropagation(containerRef.current);
});
```

### To reproduce

1. Open app in browser
2. Switch to mobile view
3. Try to swipe the drawer open
4. Nothing happens

### Expected behavior

Drawer should open by swiping

**Comment by kuukkanen** [comment]
That's odd? It worked for me when I did my changes.

**Comment by kuukkanen** [comment]
Okay, it seems like it works on Firefox but not on Chrome?
