### ISSUE TITLE
Setup: Examine Satellite API use

### ISSUE THREAD

**Issue by Noorae** [Pearl-image-comparer/Pearl#18]
Look up Satellite APIs determine witch and how to use in the project. Needs to have history data.

Add notes on how to use it for others and document any details that needs to be noted.

**Comment by kuukkanen** [comment]
There seems to be a tile layer for satellite images that can be used directly in leaflet. Set https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x} as source and it should work. I don't think it's possible to get historical images through that; though ArcGIS does provide them https://livingatlas.arcgis.com/wayback/ on their site.

**Comment by kuukkanen** [comment]
Okay, I think I figured it out now! It's possible to get all historical maps by requesting them from this https://wayback.maptiles.arcgis.com/ArcGIS/rest/services/World_Imagery/MapServer?f=json endpoint. There each map has `M` attribute which is kind of like their ID. Then, using that ID, it's possible to get the tile with this https://wayback.maptiles.arcgis.com/ArcGIS/rest/services/World_Imagery/WMTS/1.0.0/default028mm/MapServer/tile/[id]/{z}/{x}/{y}, where [id] is that ID.

**Comment by Noorae** [comment]
Does this API provide enough data? Is there enough historical data to be used in our software for example the main function of our app: comparing images of logging period to see changes?

**Comment by kuukkanen** [comment]
There seems to be images for a period of about 10 years (monthly). I don't know if that's good enough, but I'm unable to find a better resource with as good of a quality as this service.
