### ISSUE TITLE
Setup: Look up protected area data

### ISSUE THREAD

**Issue by Noorae** [Pearl-image-comparer/Pearl#19]
Look up if Laji.fi API has an endpoint or data to layer protected areas on a map view. 

Make notes for other: 
how protected areas can be shown on the map
which API to use to get the data
things to consider or additional notes

**Comment by JooRiiv** [comment]
Laji.fi does not have an endpoint or data for protected areas. They come from Syke's WMS-Service. Detailed here: https://laji.fi/en/about/5723

**Comment by JooRiiv** [comment]
I was able to add a layer to Leaflet from the address: `https://paikkatiedot.ymparisto.fi/geoserver/syke_luonnonsuojeluohjelma_alueet/wms` to show protected areas.
