### ISSUE TITLE
Setup: Copernicus API setup for satellite image layer

### ISSUE THREAD

**Issue by Noorae** [Pearl-image-comparer/Pearl#37]

**Comment by kuukkanen** [comment]
Some things to note: Copernicus uses WMS for map tiles and Leaflet takes care of that so it's no big deal. Time for which the satellite image will be sown is specified by the `time` attribute found here: https://github.com/Pearl-image-comparer/Pearl/blob/096921cd43846047a4d91ca698d4b0dcfb570408/app/components/map/_MapComponent.client.tsx#L47
