### ISSUE TITLE
Frontend: Fetch endangered species data from laji.fi API to the map

### ISSUE THREAD

**Issue by Noorae** [Pearl-image-comparer/Pearl#46]
Fetch species data from Laji.fi. You need to implement this to the client side map, because these should not go to the server. 

You do not need to implement the markers on the map, just make sure that if the species layer is selected, there is functionality to fetch species to that location on the map. 

For now, the fetched data does not need to be cleaned, lets work on that later when we know what we want to show.

**Comment by JooRiiv** [comment]
Fetch your access token from https://api.laji.fi/explorer and create a .env file on the root folder of the project.

.env file syntax:
`VITE_ACCESS_TOKEN=YOUR_ACCESS_TOKEN_HERE`
