### ISSUE TITLE
Documentation: check and document protected area color meaning from SYKE

### ISSUE THREAD

**Issue by Noorae** [Pearl-image-comparer/Pearl#49]

**Comment by teemutontti** [comment]
The explanations for the area colors can be found through this link: [Conservations area legend](https://paikkatiedot.ymparisto.fi/geoserver/syke_luonnonsuojeluohjelma_alueet/ows?service=WMS&version=1.3.0&request=GetLegendGraphic&format=image%2Fpng&width=20&height=20&layer=Luonnonsuojeluohjelmaalueet)
