### ISSUE TITLE
[Bug]: Draggable drawer not openable on pc

### ISSUE THREAD

**Issue by teemutontti** [Pearl-image-comparer/Pearl#96]
### To reproduce
1. Open application on pc
2. Drag the window to the point where the drawer switches to bottom drawer
3. Try to click or drag the bottom menu open
4. Doesn't work :(

### Expected behavior
All though the draggable menu is meant for mobile, this should work in the case a the app is used in a narrow window on pc.

### Additional context
Maybe there could be a button implemented in the draggable drawer. Note that `useMediaQuery(theme.breakpoints.down("sm"));` only detects that the viewport is narrow.

**Comment by Noorae** [comment]
There seems to be no proper solution for this as of now. And there needs to be a bigger change on how the menu works. 

The `SwipeableDrawer` that is used on small screens has inherited `pointer-events: none`. This means that you cannot click the drawer or have any clicking events on it. Any buttons added to it wont work when it is closed. If we want to override this by allowing pointer-events, it will actually prevent any dragging movements from the component, making it not swipeable.

See this: https://github.com/mui/material-ui/issues/30805

Meaning that if we add a button to the bottomDrawer, and allow  `pointer-events: all` swipe no longer works. 

We need to come up with a different idea, on how to switch between the drawers if we want the drawer to be opened and closed by swiping on mobile.

**Comment by Noorae** [comment]
Could we use something like this: https://www.npmjs.com/package/react-device-detect

and then make the mobile drawer only appear when isMobile is true? This change would keep the drawer always on the left on desktop, no matter how small the screen and then use the mobile version on touch screen?

**Comment by Noorae** [comment]
https://dev.to/cooty/a-new-way-to-test-for-touch-devices-without-javascript-enter-the-pointer-media-query-2kok

Also a possible solution.

**Comment by Noorae** [comment]
Fixed with a media query solution
